
skillMetadata:
  sections:
    - name: OpenAI GPT2 Scratch Pad
      fields:
        - type: label
          label: Requires running server https://github.com/NaxAlpha/gpt-2xy.git
        - name: gpt_url
          type: text
          label: URL
          value: "http://localhost:8080/"
          placeholder: demo prompt in the input box
    
